spring:
  profiles:
    active: ${ACTIVE_PROFILE:prod}
  datasource:
    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DB}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 5 
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        jdbc:
          time_zone: Asia/Kolkata
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1

  azure:
    storage:
      container:
        name: greensupermarketblogcontainer
      connection:
        string: DefaultEndpointsProtocol=https;AccountName=greensupermarketstoreacc;AccountKey=fGIpZLaa/xXYrR/98HuVDVRWfUmEPHhRWlnYesob00ejEAh04jk6wm9HZVpb9s3u6hq3wC/hLitE+AStuQifMA==;EndpointSuffix=core.windows.net