#Database
MYSQL_USERNAME: ${{ secrets.MYSQL_USERNAME }}
MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
MYSQL_HOST: ${{ secrets.MYSQL_HOST }}
MYSQL_PORT: ${{ secrets.MYSQL_PORT }}
MYSQL_DB: ${{ secrets.MYSQL_DB }}

#AZURE
AZURE_BASE_URI: ${{ secrets.AZURE_BASE_URI }}
AZURE_CONNECTION_STRING: ${{ secrets.AZURE_CONNECTION_STRING }}
AZURE_CONTAINER: ${{ secrets.AZURE_CONTAINER }}

#SERVER
SERVER_PORT: ${{ secrets.SERVER_PORT }}
ACTIVE_PROFILE: ${{ secrets.ACTIVE_PROFILE }}

#Email Config
EMAIL_HOST: ${{ secrets.EMAIL_HOST }}
EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
EMAIL_PORT: ${{ secrets.EMAIL_PORT }}
EMAIL_USERNAME: ${{ secrets.EMAIL_USERNAME }}

#JWT
JWT_SECRET: ${{ secrets.JWT_SECRET }}