spring:
  datasource:
    url: jdbc:mysql://greensupermarket-mysqlserver-dev.mysql.database.azure.com:3306/greensupermarket-db-dev?sslMode=REQUIRED
    username: mysql_admin_dev@greensupermarket-mysqlserver-dev
    password: Lithara@2002
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 5 
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1

  azure:
    storage:
      container:
        name: greensupermarketblogcontainer
      connection:
        string: DefaultEndpointsProtocol=https;AccountName=greensupermarketstoreacc;AccountKey=fGIpZLaa/xXYrR/98HuVDVRWfUmEPHhRWlnYesob00ejEAh04jk6wm9HZVpb9s3u6hq3wC/hLitE+AStuQifMA==;EndpointSuffix=core.windows.net